apiVersion: v1
data:
  # echo -n "internal-authentication-db-app-user" | base64
  password: aW50ZXJuYWwtYXV0aGVudGljYXRpb24tZGItYXBwLXVzZXI=
  username: aW50ZXJuYWwtYXV0aGVudGljYXRpb24tZGItYXBwLXVzZXI=
kind: Secret
metadata:
  name: internal-authentication-db-app-user
type: kubernetes.io/basic-auth
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: internal-authentication-db

spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5

  postgresql:
    parameters:
      random_page_cost: "1.1"
      log_statement: "ddl"
      log_checkpoints: "on"

  storage:
    storageClass: "nfs-rwx"
    size: "2Gi"

  bootstrap:
    initdb:
      database: app
      owner: internal-authentication-db-app-user
      secret:
        name: internal-authentication-db-app-user

  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: false

# delete with :
#    kubectl delete cluster.postgresql.cnpg.io internal-authentication-db -n testing-dev
#   kubectl delete secret internal-authentication-db-app-user -n testing-dev